### ISSUE TITLE
every time i load it i get an error below

### ISSUE THREAD

**Issue by cyberze** [andrepl/LivestockLock#1]
[SEVERE] Error occurred while enabling LivestockLock v0.0.6 (Is it up to date?)
java.lang.IllegalStateException: No match found
    at java.util.regex.Matcher.group(Matcher.java:485)
    at com.norcode.bukkit.livestocklock.LivestockLock.loadConfig(LivestockLock.java:145)
    at com.norcode.bukkit.livestocklock.LivestockLock.onEnable(LivestockLock.java:42)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:382)
    at org.bukkit.craftbukkit.v1_6_R2.CraftServer.loadPlugin(CraftServer.java:286)
    at org.bukkit.craftbukkit.v1_6_R2.CraftServer.enablePlugins(CraftServer.java:268)
    at net.minecraft.server.v1_6_R2.MinecraftServer.l(MinecraftServer.java:319)
    at net.minecraft.server.v1_6_R2.MinecraftServer.f(MinecraftServer.java:296)
    at net.minecraft.server.v1_6_R2.MinecraftServer.a(MinecraftServer.java:256)
    at net.minecraft.server.v1_6_R2.DedicatedServer.init(DedicatedServer.java:164)
    at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:397)
    at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)

**Comment by andrepl** [comment]
do you have: `unused-claim-expiry` in your config file?
it should be: 

```
unused-claim-expiry: 0d
```

if you don't want them to expire.  it's possible this setting wasn't added automatically after an upgrade, I'll try to fix that and do a new release.

**Comment by cyberze** [comment]
my config, i run on 1.6.2 within centos enviroment if that makes any
diffrence ;d

debug: false
require-adulthood: true
require-taming: true
auto-claim-on-tame: true
unused-claim-expiry: 0d
despawn-expired-claims: false
group-limits:
  member: 10
  vip: 20
allowed-entity-types:
  pig:
    entity-type-id: 90
    cost-money: 5.0
    cost-xp: 0
  wolf:
    entity-type-id: 95
    cost-money: 5.0
    cost-xp: 0
  cat:
    entity-type-id: 98
    cost-money: 5.0
    cost-xp: 0
  cow:
    entity-type-id: 92
    cost-money: 5.0
    cost-xp: 0
  sheep:
    entity-type-id: 91
    cost-money: 5.0
  mushroom-cow:
    entity-type-id: 96
    cost-money: 5.0
  chicken:
    entity-type-id: 93
    cost-money: 5.0
  horse:
    entity-type-id: 100
    cost-money: 10

2013/8/1 andrepl notifications@github.com

**Comment by andrepl** [comment]
Fixed it here https://github.com/andrepl/LivestockLock/commit/343771945ff74db069f32adecaf8c1d650af8cfc

there's a development build here: http://mcgitlab.norcode.com:8081/job/LivestockLock/lastSuccessfulBuild/
and a new release has been uploaded to bukkitdev for approval. thanks for the report.

**Comment by cyberze** [comment]
awesome man :D and that was the quickest develper answer i got so far :D

2013/8/1 andrepl notifications@github.com

**Comment by andrepl** [comment]
It was a silly bug, I'm not sure how it got by initial testing..

also a good bug report with an actual, complete stack trace really helps, so thanks again for that :)
