### ISSUE TITLE
/lsl list <player> error

### ISSUE THREAD

**Issue by AustinShalit** [andrepl/LivestockLock#2]
I keep getting this error when I run /lsl list player

08:33:36 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'lsl' in plugin LivestockLock v0.0.7
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:191)
        at org.bukkit.craftbukkit.v1_6_R2.CraftServer.dispatchCommand(CraftServer.java:523)
        at net.minecraft.server.v1_6_R2.PlayerConnection.handleCommand(PlayerConnection.java:962)
        at net.minecraft.server.v1_6_R2.PlayerConnection.chat(PlayerConnection.java:880)
        at net.minecraft.server.v1_6_R2.PlayerConnection.a(PlayerConnection.java:837)
        at net.minecraft.server.v1_6_R2.Packet3Chat.handle(SourceFile:49)
        at net.minecraft.server.v1_6_R2.NetworkManager.b(NetworkManager.java:296)
        at net.minecraft.server.v1_6_R2.PlayerConnection.e(PlayerConnection.java:116)
        at net.minecraft.server.v1_6_R2.ServerConnection.b(SourceFile:37)
        at net.minecraft.server.v1_6_R2.DedicatedServerConnection.b(SourceFile:30)
        at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:590)
        at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:226)
        at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:486)
        at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:419)
        at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
Caused by: java.lang.NullPointerException
        at com.norcode.bukkit.livestocklock.commands.ListCommand.onCommand(ListCommand.java:54)
        at com.norcode.bukkit.livestocklock.LivestockLock.onCommand(LivestockLock.java:179)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
        ... 15 more

**Comment by andrepl** [comment]
I haven't been able to reproduce this, Can you try the latest development build here: http://mcgitlab.norcode.com:8081/job/LivestockLock/ and see if it fixes the issue?
